import Head from 'next/head';
import Image from 'next/image';
import styles from '@/styles/Home.module.css';
import { QRCode } from 'react-qrcode-logo';
import { ethers, utils } from 'ethers';
import { useContext, useEffect, useState } from 'react';
import { AppContext } from '@/components/contexts/AppContext';
import ConnectWallet from '@/components/web3/ConnectWallet';
import { treasureTrailsABI } from '@/components/abi/tresureABI';
import Scan from '@/components/utils/Scan';

const contractAdd = '0x03e51903afa7A26E51DbaC52826B715A300B9326';

export default function Home() {
  const { account, signer } = useContext(AppContext);
  const [tickets, setTickets] = useState([]);
  const [ticket, setTicket] = useState(null);
  const [ticketIndex, setTicketIndex] = useState(0);
  const [id, setId] = useState('');
  const [openCamera, setOpenCamera] = useState(false);

  const [ttl, setTtl] = useState();
  const [data, setData] = useState('');

  useEffect(() => {
    if (signer) {
      const myTreasureTrailsXP = new ethers.Contract(
        contractAdd,
        treasureTrailsABI,
        signer
      );
      setTtl(myTreasureTrailsXP);
    }
  }, [signer]);

  useEffect(() => {
    if (data !== '') {
      const theticket = tickets.find((t, i) => i === parseInt(data));
      console.log('theticket', theticket);
      if (theticket) buyTicket(data);
      setData('');
      setOpenCamera(false);
    }
  }, [data, tickets]);

  const getTickets = async () => {
    try {
      const xx2 = await ttl?.getTickets();
      console.log('xx2 :>> ', xx2);
      setTickets(xx2);
    } catch (error) {
      console.log(error);
    }
  };

  const buyTicket = async (ticketId) => {
    try {
      await ttl?.buyTicket(ticketId, { value: utils.parseEther('0.01') });
    } catch (error) {
      console.log(error);
    }
  };
  const addTicket = async () => {
    try {
      const name = 'Third Ticket';
      const date = new Date();
      date.setHours(date.getHours() + 4);
      console.log('name', name);
      const tx1 = await ttl?.addTicket(
        name,
        utils.parseEther('0.01'),
        date.getTime(),
        50
      );
      tx1.wait();
      console.log('name2', name);
    } catch (error) {
      console.log(error);
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {!account && (
          <div className="flex items-center justify-center py-10">
            <ConnectWallet />
          </div>
        )}

        <div className={styles.description}>
          {openCamera && <Scan setId={setData} />}
          <p>
            Get started by editing&nbsp;
            <button onClick={getTickets}>tickets</button>
            <button onClick={() => buyTicket(2)}>BUY</button>
            <button onClick={addTicket}>ADD</button>
            <button onClick={() => setOpenCamera(true)}>OPEN</button>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Docs <span>-&gt;</span>
            </h2>
            <p>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Learn <span>-&gt;</span>
            </h2>
            <p>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Templates <span>-&gt;</span>
            </h2>
            <p>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Deploy <span>-&gt;</span>
            </h2>
            <p>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
            <QRCode
              value="2"
              logoImage="https://www.gonzalobarria.com/images/logo-gb.jpg"
              eyeRadius={[
                {
                  // top/left eye
                  outer: [10, 10, 0, 10],
                  inner: [10, 10, 0, 10],
                },
                [10, 10, 10, 0], // top/right eye
                [10, 0, 10, 10], // bottom/left
              ]}
            />
          </a>
        </div>
      </main>
    </>
  );
}
